PageBlockAttribute:
    type: interface
    config:
        fields:
            id:
                type: String
            name:
                type: String
            value:
                type: String
        resolveType: "@=resolver('PageBlockAttributeType', [value, context])"

BasePageBlockAttribute:
    type: object
    config:
        interfaces: [PageBlockAttribute]
        fields:
            id:
                type: String
            name:
                type: String
            value:
                type: String

#IntegerPageBlockAttribute:
#StringPageBlockAttribute:
#UrlPageBlockAttribute:
#TextPageBlockAttribute:

EmbedPageBlockAttribute:
    type: object
    inherits: [BasePageBlockAttribute]
    config:
        interfaces: [PageBlockAttribute]
        fields:
            content:
                type: "DomainContent"
                resolve: "@=resolver('ContentById', [value.getValue()])"