services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        EzSystems\EzPlatformGraphQL\Schema\Worker:
            tags:
                - { name: ezplatform_graphql.domain_schema_worker }
        BD\EzPlatformGraphQLPage\GraphQL\Schema\Worker\BaseWorker:
            calls:
                - [setNameHelper, ['@BD\EzPlatformGraphQLPage\GraphQL\Schema\Worker\NameHelper']]

    BD\EzPlatformGraphQLPage\GraphQL\Schema\Worker\:
        resource: ../../GraphQL/Schema/Worker/*

    BD\EzPlatformGraphQLPage\GraphQL\PageFieldValueBuilder:
        tags:
            - { name: ezplatform_graphql.field_value_builder, type: 'ezpage'}
            - { name: ezplatform_graphql.field_value_builder, type: 'ezlandingpage'}

    BD\EzPlatformGraphQLPage\GraphQL\PageResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "PageBlockAttributeType", method: "resolvePageBlockAttributeType" }
            - { name: overblog_graphql.resolver, alias: "PageBlockAttributes", method: "resolvePageBlockAttributes" }
            - { name: overblog_graphql.resolver, alias: "PageBlockType", method: "resolvePageBlockType" }

    BD\EzPlatformGraphQLPage\GraphQL\Schema\DomainIterator:
        tags:
            - { name: ezplatform_graphql.schema_domain_iterator }