services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    BD\EzPlatformGraphQLPage\GraphQL\PageFieldValueBuilder:
        tags:
            - { name: ezplatform_graphql.field_value_builder, type: 'ezpage'}
            - { name: ezplatform_graphql.field_value_builder, type: 'ezlandingpage'}

    BD\EzPlatformGraphQLPage\GraphQL\PageResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "PageBlockAttributeType", method: "resolvePageBlockAttributeType" }
            - { name: overblog_graphql.resolver, alias: "PageBlockAttributes", method: "resolvePageBlockAttributes" }
            - { name: overblog_graphql.resolver, alias: "PageBlockType", method: "resolvePageBlockType" }

