PageZone:
    type: object
    config:
        fields:
            id:
                type: Int
            name:
                type: String
            blocks:
                type: "[PageBlockValue]"